services:
  acc-franchise-api:
    image: acc-franchise-api:0.1.0
    build: .
    container_name: acc-franchise-api
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: local
