spring:
  datasource:
    url: jdbc:mysql://localhost:3307/acc_franchise?useSSL=false&allowPublicKeyRetrieval=true
    username: acc_user
    password: acc_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
