spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/acc_franchise
    username: acc_user
    password: acc_password

  # ðŸš« Nunca crear/modificar tablas desde la app
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG
